module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    ADMIN_COLLECTION:'admin',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISH_COLLECTION:'wish',
    COUPON_COLLECTION:'coupon',
    BANNER_COLLECTION:'banner'
}
